name: Publish to Maven
on:
  release:
    types: [created]
  workflow_dispatch:    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: olafurpg/setup-scala@v13

      - name: Set up Node 14
        uses: actions/setup-node@v3
        with:
          node-version: 14        

      - name: Publish package
        run: |
          sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          PGP_SECRET: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          SONATYPE_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          SONATYPE_USERNAME: ${{ secrets.OSSRH_USERNAME }}
